
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with ruff and mypy
      run: |
        pip install ruff mypy
        ruff .
        mypy src/
    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov
        pytest --cov=src --cov-report=term-missing
